shared:
    image: node:8

parameters:
  _started_at: simple
  user:
      value: adong
      description: User running build

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - test: echo ok
            - p1:  echo $(meta get parameters._started_at)
            - p2:  echo $(meta get parameters.user)
